---
- name: Create directories for service files
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop: "{{ proxmox_vgpu_service_files_dirs }}"

- name: Import service files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: u=rwx,g=rwx,o=rwx
  loop: "{{ proxmox_vgpu_service_files }}"
