---
name: Validate Role

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  line:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies.
        run: pip3 install yamllint ansible-lint

      - name: Run ansible-lint
        run: ansible-lint .
        
      - name: Run yamllint
        run: yamllint .
